version: '3'
services:
  python-scraper-example:
    build: ./python-scraper-example
    networks:
      selenoid: null
  ggr:
    image: aerokube/ggr
    volumes:
      - "./ggr-config:/etc/grid-router:ro"
    ports:
      - "4446:4444"
    networks:
      selenoid: null
  ggr-ui:
    image: aerokube/ggr-ui
    volumes:
      - "./ggr-config/quota:/etc/grid-router/quota:ro"
    ports:
      - "8888:8888"
    networks:
      selenoid: null
  selenoid:
    image: aerokube/selenoid
    volumes:
      - "./selenoid-config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid-config/video:/opt/selenoid/video"
      - "./selenoid-config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/selenoid-config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid", "-limit", "2", "-cpu", "1.0" ]
    ports:
      - "4445:4444"
    networks:
      selenoid: null
  selenoid-ui:
    image: aerokube/selenoid-ui
    command: [ "--selenoid-uri", "http://test:test-password@ggr-ui:8888" ]
    ports:
      - "8080:8080"
    networks:
      selenoid: null
networks:
  selenoid:
    external:
      name: selenoid
